/**
 * GoGood Checkin API
 * This API allows clients to checkin through the GoGood API
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CheckinRequest model module.
 * @module model/CheckinRequest
 * @version 1
 */
class CheckinRequest {
    /**
     * Constructs a new <code>CheckinRequest</code>.
     * @alias module:model/CheckinRequest
     */
    constructor() { 
        
        CheckinRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CheckinRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckinRequest} obj Optional instance to populate.
     * @return {module:model/CheckinRequest} The populated <code>CheckinRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckinRequest();

            if (data.hasOwnProperty('application_id')) {
                obj['application_id'] = ApiClient.convertToType(data['application_id'], 'String');
            }
            if (data.hasOwnProperty('application_secret')) {
                obj['application_secret'] = ApiClient.convertToType(data['application_secret'], 'String');
            }
            if (data.hasOwnProperty('partner_token')) {
                obj['partner_token'] = ApiClient.convertToType(data['partner_token'], 'String');
            }
            if (data.hasOwnProperty('user_token')) {
                obj['user_token'] = ApiClient.convertToType(data['user_token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CheckinRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CheckinRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['application_id'] && !(typeof data['application_id'] === 'string' || data['application_id'] instanceof String)) {
            throw new Error("Expected the field `application_id` to be a primitive type in the JSON string but got " + data['application_id']);
        }
        // ensure the json data is a string
        if (data['application_secret'] && !(typeof data['application_secret'] === 'string' || data['application_secret'] instanceof String)) {
            throw new Error("Expected the field `application_secret` to be a primitive type in the JSON string but got " + data['application_secret']);
        }
        // ensure the json data is a string
        if (data['partner_token'] && !(typeof data['partner_token'] === 'string' || data['partner_token'] instanceof String)) {
            throw new Error("Expected the field `partner_token` to be a primitive type in the JSON string but got " + data['partner_token']);
        }
        // ensure the json data is a string
        if (data['user_token'] && !(typeof data['user_token'] === 'string' || data['user_token'] instanceof String)) {
            throw new Error("Expected the field `user_token` to be a primitive type in the JSON string but got " + data['user_token']);
        }

        return true;
    }


}



/**
 * The unique application ID provided by GoGood
 * @member {String} application_id
 */
CheckinRequest.prototype['application_id'] = undefined;

/**
 * The unique application secret provided by GoGood
 * @member {String} application_secret
 */
CheckinRequest.prototype['application_secret'] = undefined;

/**
 * The partner token inserted in your application by the client
 * @member {String} partner_token
 */
CheckinRequest.prototype['partner_token'] = undefined;

/**
 * The user token inserted in your application in the user first use of the gym
 * @member {String} user_token
 */
CheckinRequest.prototype['user_token'] = undefined;






export default CheckinRequest;

