/**
 * GoGood Checkin API
 * This API allows clients to checkin through the GoGood API
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CheckinSuccessResponse model module.
 * @module model/CheckinSuccessResponse
 * @version 1
 */
class CheckinSuccessResponse {
    /**
     * Constructs a new <code>CheckinSuccessResponse</code>.
     * @alias module:model/CheckinSuccessResponse
     */
    constructor() { 
        
        CheckinSuccessResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CheckinSuccessResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckinSuccessResponse} obj Optional instance to populate.
     * @return {module:model/CheckinSuccessResponse} The populated <code>CheckinSuccessResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckinSuccessResponse();

            if (data.hasOwnProperty('partner_token')) {
                obj['partner_token'] = ApiClient.convertToType(data['partner_token'], 'String');
            }
            if (data.hasOwnProperty('user_token')) {
                obj['user_token'] = ApiClient.convertToType(data['user_token'], 'String');
            }
            if (data.hasOwnProperty('checked_in')) {
                obj['checked_in'] = ApiClient.convertToType(data['checked_in'], 'Boolean');
            }
            if (data.hasOwnProperty('checked_at')) {
                obj['checked_at'] = ApiClient.convertToType(data['checked_at'], 'Date');
            }
            if (data.hasOwnProperty('partner')) {
                obj['partner'] = ApiClient.convertToType(data['partner'], 'String');
            }
            if (data.hasOwnProperty('modality_alias')) {
                obj['modality_alias'] = ApiClient.convertToType(data['modality_alias'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CheckinSuccessResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CheckinSuccessResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['partner_token'] && !(typeof data['partner_token'] === 'string' || data['partner_token'] instanceof String)) {
            throw new Error("Expected the field `partner_token` to be a primitive type in the JSON string but got " + data['partner_token']);
        }
        // ensure the json data is a string
        if (data['user_token'] && !(typeof data['user_token'] === 'string' || data['user_token'] instanceof String)) {
            throw new Error("Expected the field `user_token` to be a primitive type in the JSON string but got " + data['user_token']);
        }
        // ensure the json data is a string
        if (data['partner'] && !(typeof data['partner'] === 'string' || data['partner'] instanceof String)) {
            throw new Error("Expected the field `partner` to be a primitive type in the JSON string but got " + data['partner']);
        }
        // ensure the json data is a string
        if (data['modality_alias'] && !(typeof data['modality_alias'] === 'string' || data['modality_alias'] instanceof String)) {
            throw new Error("Expected the field `modality_alias` to be a primitive type in the JSON string but got " + data['modality_alias']);
        }

        return true;
    }


}



/**
 * The partner token inserted in your application by the client
 * @member {String} partner_token
 */
CheckinSuccessResponse.prototype['partner_token'] = undefined;

/**
 * The user token inserted in your application in the user first use of the gym
 * @member {String} user_token
 */
CheckinSuccessResponse.prototype['user_token'] = undefined;

/**
 * True if the check in was validated
 * @member {Boolean} checked_in
 */
CheckinSuccessResponse.prototype['checked_in'] = undefined;

/**
 * The exact time in which the check-in has been validated by GoGood
 * @member {Date} checked_at
 */
CheckinSuccessResponse.prototype['checked_at'] = undefined;

/**
 * The name of the gym partner where your check-in has been realized
 * @member {String} partner
 */
CheckinSuccessResponse.prototype['partner'] = undefined;

/**
 * A string with the name of the modality in which the user has checked-in
 * @member {String} modality_alias
 */
CheckinSuccessResponse.prototype['modality_alias'] = undefined;






export default CheckinSuccessResponse;

