/**
 * GoGood Checkin API
 * This API allows clients to checkin through the GoGood API
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CheckinFailedResponse400.
* @enum {}
* @readonly
*/
export default class CheckinFailedResponse400 {
    
        /**
         * value: "Error saving the validated token"
         * @const
         */
        "Error saving the validated token" = "Error saving the validated token";

    
        /**
         * value: "Partner token invalid"
         * @const
         */
        "Partner token invalid" = "Partner token invalid";

    
        /**
         * value: "User token invalid"
         * @const
         */
        "User token invalid" = "User token invalid";

    
        /**
         * value: "User has not checked in today"
         * @const
         */
        "User has not checked in today" = "User has not checked in today";

    
        /**
         * value: "User has checked in to another partner"
         * @const
         */
        "User has checked in to another partner" = "User has checked in to another partner";

    
        /**
         * value: "User has already checked in today"
         * @const
         */
        "User has already checked in today" = "User has already checked in today";

    
        /**
         * value: "Checkin has expired"
         * @const
         */
        "Checkin has expired" = "Checkin has expired";

    

    /**
    * Returns a <code>CheckinFailedResponse400</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CheckinFailedResponse400} The enum <code>CheckinFailedResponse400</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

