/**
 * GoGood Checkin API
 * This API allows clients to checkin through the GoGood API
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CheckinFailedResponse500.
* @enum {}
* @readonly
*/
export default class CheckinFailedResponse500 {
    
        /**
         * value: "Error saving the validated token"
         * @const
         */
        "Error saving the validated token" = "Error saving the validated token";

    

    /**
    * Returns a <code>CheckinFailedResponse500</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CheckinFailedResponse500} The enum <code>CheckinFailedResponse500</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

