/**
 * GoGood Checkin API
 * This API allows clients to checkin through the GoGood API
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CheckinFailedResponse400 from '../model/CheckinFailedResponse400';
import CheckinFailedResponse401 from '../model/CheckinFailedResponse401';
import CheckinFailedResponse500 from '../model/CheckinFailedResponse500';
import CheckinSuccessResponse from '../model/CheckinSuccessResponse';

/**
* Default service.
* @module api/DefaultApi
* @version 1
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the checkinHook operation.
     * @callback module:api/DefaultApi~checkinHookCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CheckinSuccessResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Validates and checks in an user to a given business
     * A user token and a business token are received and the access is validated and, if everything is correct, the user is checked in into the partner.
     * @param {module:api/DefaultApi~checkinHookCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CheckinSuccessResponse}
     */
    checkinHook(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CheckinSuccessResponse;
      return this.apiClient.callApi(
        '//checkin/validate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
