/**
 * GoGood Checkin API
 * This API allows clients to checkin through the GoGood API
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GoGoodCheckinApi);
  }
}(this, function(expect, GoGoodCheckinApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GoGoodCheckinApi.CheckinSuccessResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CheckinSuccessResponse', function() {
    it('should create an instance of CheckinSuccessResponse', function() {
      // uncomment below and update the code to test CheckinSuccessResponse
      //var instance = new GoGoodCheckinApi.CheckinSuccessResponse();
      //expect(instance).to.be.a(GoGoodCheckinApi.CheckinSuccessResponse);
    });

    it('should have the property partnerToken (base name: "partner_token")', function() {
      // uncomment below and update the code to test the property partnerToken
      //var instance = new GoGoodCheckinApi.CheckinSuccessResponse();
      //expect(instance).to.be();
    });

    it('should have the property userToken (base name: "user_token")', function() {
      // uncomment below and update the code to test the property userToken
      //var instance = new GoGoodCheckinApi.CheckinSuccessResponse();
      //expect(instance).to.be();
    });

    it('should have the property checkedIn (base name: "checked_in")', function() {
      // uncomment below and update the code to test the property checkedIn
      //var instance = new GoGoodCheckinApi.CheckinSuccessResponse();
      //expect(instance).to.be();
    });

    it('should have the property checkedAt (base name: "checked_at")', function() {
      // uncomment below and update the code to test the property checkedAt
      //var instance = new GoGoodCheckinApi.CheckinSuccessResponse();
      //expect(instance).to.be();
    });

    it('should have the property partner (base name: "partner")', function() {
      // uncomment below and update the code to test the property partner
      //var instance = new GoGoodCheckinApi.CheckinSuccessResponse();
      //expect(instance).to.be();
    });

    it('should have the property modalityAlias (base name: "modality_alias")', function() {
      // uncomment below and update the code to test the property modalityAlias
      //var instance = new GoGoodCheckinApi.CheckinSuccessResponse();
      //expect(instance).to.be();
    });

  });

}));
